# azure-pipelines.yml

trigger:
- master

pr:
- '*'

pool:
  vmImage: 'windows-latest'  # Use a Windows VM image

jobs:
- job: BuildArtifact
  displayName: 'Build Artifact'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.315.414'
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: 'Use .NET SDK'

  - script: |
      echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet'
      dotnet tool install --global Java
      dotnet tool install --global Maven
      echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet/.store/javalang.jdk'
      echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet/.store/javalang.maven'
    displayName: 'Install Java and Maven'

  - script: 'mvn clean package -DskipTests=true'
    displayName: 'Maven Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/path/to/artifact'  # Replace with the actual path to your artifact
      artifactName: 'my-artifact'
